[package]
name = "rcore32"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>"]
edition = "2018"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
