[package]
name = "rcore32"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>"]
edition = "2018"

[dependencies]
riscv = { git = "https://github.com/riscv-and-rust-and-decaf/riscv" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
