[package]
name = "rcore32"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.14"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
